name: Destroy ECS

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  terraform:
    name: Destroy Terraform
    runs-on: ubuntu-latest

    env:  # Define environment variables for AWS
      AWS_REGION: us-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Using GitHub Secrets for AWS Access Key
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}  # Using GitHub Secrets for AWS Secret Key

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}  
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}  
          aws-region: ${{ env.AWS_REGION }}  

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./4-load-balancer

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./4-load-balancer

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch'  # Destroy when manually triggered
        run: terraform destroy -auto-approve
        working-directory: ./4-load-balancer
